// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { HealthHealthGetData, HealthHealthGetResponses, LoginApiAuthLoginPostData, LoginApiAuthLoginPostErrors, LoginApiAuthLoginPostResponses, RouteDeleteUserApiUsersUserIdDeleteData, RouteDeleteUserApiUsersUserIdDeleteErrors, RouteDeleteUserApiUsersUserIdDeleteResponses, RouteGetUserApiUsersUserIdGetData, RouteGetUserApiUsersUserIdGetErrors, RouteGetUserApiUsersUserIdGetResponses, RouteListUsersApiUsersGetData, RouteListUsersApiUsersGetResponses, SignupApiAuthSignupPostData, SignupApiAuthSignupPostErrors, SignupApiAuthSignupPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Signup
 */
export const signupApiAuthSignupPost = <ThrowOnError extends boolean = false>(options: Options<SignupApiAuthSignupPostData, ThrowOnError>) => (options.client ?? client).post<SignupApiAuthSignupPostResponses, SignupApiAuthSignupPostErrors, ThrowOnError>({
    url: '/api/auth/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiAuthLoginPostResponses, LoginApiAuthLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Route List Users
 */
export const routeListUsersApiUsersGet = <ThrowOnError extends boolean = false>(options?: Options<RouteListUsersApiUsersGetData, ThrowOnError>) => (options?.client ?? client).get<RouteListUsersApiUsersGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/',
    ...options
});

/**
 * Route Delete User
 */
export const routeDeleteUserApiUsersUserIdDelete = <ThrowOnError extends boolean = false>(options: Options<RouteDeleteUserApiUsersUserIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<RouteDeleteUserApiUsersUserIdDeleteResponses, RouteDeleteUserApiUsersUserIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{user_id}',
    ...options
});

/**
 * Route Get User
 */
export const routeGetUserApiUsersUserIdGet = <ThrowOnError extends boolean = false>(options: Options<RouteGetUserApiUsersUserIdGetData, ThrowOnError>) => (options.client ?? client).get<RouteGetUserApiUsersUserIdGetResponses, RouteGetUserApiUsersUserIdGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{user_id}',
    ...options
});
