// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_api_auth_login_post
 */
export type BodyLoginApiAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SignupRequest
 */
export type SignupRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password Hash
     */
    password_hash: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SignupApiAuthSignupPostData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupApiAuthSignupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupApiAuthSignupPostError = SignupApiAuthSignupPostErrors[keyof SignupApiAuthSignupPostErrors];

export type SignupApiAuthSignupPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SignupApiAuthSignupPostResponse = SignupApiAuthSignupPostResponses[keyof SignupApiAuthSignupPostResponses];

export type LoginApiAuthLoginPostData = {
    body: BodyLoginApiAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type RouteListUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type RouteListUsersApiUsersGetResponses = {
    /**
     * Response Route List Users Api Users  Get
     *
     * Successful Response
     */
    200: Array<User>;
};

export type RouteListUsersApiUsersGetResponse = RouteListUsersApiUsersGetResponses[keyof RouteListUsersApiUsersGetResponses];

export type RouteDeleteUserApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type RouteDeleteUserApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RouteDeleteUserApiUsersUserIdDeleteError = RouteDeleteUserApiUsersUserIdDeleteErrors[keyof RouteDeleteUserApiUsersUserIdDeleteErrors];

export type RouteDeleteUserApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RouteGetUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type RouteGetUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RouteGetUserApiUsersUserIdGetError = RouteGetUserApiUsersUserIdGetErrors[keyof RouteGetUserApiUsersUserIdGetErrors];

export type RouteGetUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type RouteGetUserApiUsersUserIdGetResponse = RouteGetUserApiUsersUserIdGetResponses[keyof RouteGetUserApiUsersUserIdGetResponses];
