import os
import pandas as pd
import plotly.express as px
import plotly.io as pio

# Define paths
current_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.abspath(os.path.join(current_dir, ".."))
OUTPUT_DIR = os.path.join(repo_root, "outputs")

def generate_visualization():
    print("Loading predictions...")
    input_path = os.path.join(OUTPUT_DIR, "global_map_predictions.csv")
    df = pd.read_csv(input_path)
    
    print(f"Loaded {len(df)} points.")
    
    # 1. Create Interactive Map
    print("Generating map...")
    fig = px.scatter_geo(
        df,
        lat="lat_dec",
        lon="long_dec",
        color="predicted_rate",
        hover_name="soil.classification",
        hover_data=["AMT", "AMP"],
        color_continuous_scale="Viridis",
        title="Global Potential Carbon Accumulation Rates (Mg C ha-1 yr-1)",
        projection="natural earth"
    )
    
    fig.update_layout(
        margin={"r":0,"t":40,"l":0,"b":0},
        coloraxis_colorbar=dict(title="Rate (Mg C/ha/yr)")
    )
    
    # Get HTML for the map
    map_html = pio.to_html(fig, full_html=False, include_plotlyjs='cdn')
    
    # 2. Create Summary Table
    print("Generating summary table...")
    # Let's show the top 20 locations with highest potential
    top_20 = df.sort_values(by="predicted_rate", ascending=False).head(20)
    table_html = top_20.to_html(classes="table table-striped table-hover", index=False)
    
    # 3. Assemble Final HTML
    print("Assembling final HTML report...")
    final_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>GROA Carbon Map Results</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {{ font-family: sans-serif; padding: 20px; }}
            .map-container {{ width: 100%; height: 600px; margin-bottom: 20px; }}
            h1 {{ margin-bottom: 20px; }}
            h2 {{ margin-top: 30px; margin-bottom: 15px; }}
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <h1>Global Natural Forest Regrowth Carbon Potential</h1>
            <p class="lead">Interactive map showing predicted carbon accumulation rates (Mg C ha<sup>-1</sup> yr<sup>-1</sup>) for the first 30 years of regrowth.</p>
            
            <div class="card shadow-sm mb-4">
                <div class="card-header">Global Map</div>
                <div class="card-body">
                    {map_html}
                </div>
            </div>
            
            <h2>Top 20 Locations with Highest Potential</h2>
            <div class="table-responsive">
                {table_html}
            </div>
            
            <footer class="mt-5 text-muted text-center">
                <p>Generated by GROA Mapping Pipeline</p>
            </footer>
        </div>
    </body>
    </html>
    """
    
    output_html_path = os.path.join(OUTPUT_DIR, "global_carbon_map_report.html")
    with open(output_html_path, "w", encoding="utf-8") as f:
        f.write(final_html)
        
    print(f"Visualization saved to: {output_html_path}")

if __name__ == "__main__":
    generate_visualization()
